### ISSUE TITLE
English translations ?

### ISSUE THREAD

**Issue by ghedwards** [simplezhli/flutter_deer#118]
### 运行环境 ###

- [x] 电脑系统：如：`Windows 10`
- [x] 设备型号：如：`小米MIX 2s`
- [x] 设备系统版本：如 `Android 10`
- [x] Flutter 版本：如 `1.12.13+hotfix.9`

**Comment by simplezhli** [comment]
@ghedwards Can you give me some advice?

## Content

* mvp mode
* Use `provider`(version 4.x) for state management
* Network request encapsulation based on `dio` (version 3.x)
* Driver testing, accessibility testing.
* Support dark mode
* Use `Sliver` series of components to achieve complex scrolling effects
* Use amap Positioning to select address
* Pull down to refresh + pull up to load more
* Check update
* PopupWindow
* Scan code（barcode_scan plugin）
* Menu switching animation (circular diffusion, 3D flip)
* Sliding delete
* City selection
* Similar to the three-level linkage of Jingdong's choice of cities
* Custom Dialog
* Sticky headers
* Password input keyboard
* Verification code input
* Custom Simple Calendar
* Graphs and [pie charts](https://dartpad.cn/d06f8f737d6eb2d87978eb2d14b87864)
* Modular routing management
* More optimization


Android package：[Click to download](https://www.pgyer.com/gYXj)，Password: `111111`。

iOS needs to download the code to run.

## Project environment

[![Build Status](https://github.com/simplezhli/flutter_deer/workflows/flutter_deer%20driver/badge.svg?branch=master)](https://github.com/simplezhli/flutter_deer/actions?query=workflow%3A%22flutter_deer+driver%22+branch%3Amaster)

    1. Flutter version 1.17.1
     
    2. Dart version 2.8.2

## Precautions

- `debug` There will be some stuck phenomenon in the mode, which is normal. A good experience requires a `release` package. iOS can execute commands `flutter build ios` to create `release` versions. Android can execute commands `flutter build apk` to create `release` versions.

- If there is a problem with the project, you can try to find a solution in the [iOS problem summary](./iOS问题汇总.md) and [Android problem summary](./Android问题汇总.md).

- Due to some plug-ins, this project has imperfect support on the web (mainly in terms of functionality, and UI issues are minor). Those who are interested can run the experience by themselves.
        
- Because there are a lot of pages, some pages may not be found at the beginning. (You can execute integration test commands to `flutter drive --profile --target=test_driver/driver.dart` view function demonstrations)

- I have added a relative path to the design drawings in the page notes. I can search or find the corresponding page. I hope it will help you.

- This project uses the FlutterJsonBeanFactory plugin to generate beans.

**Comment by ghedwards** [comment]
What would you like advice on? on quick glance the text appears to be ok, not sure what you mean by "stuck phenomenon" in the text "There will be some stuck phenomenon in the mode, which is normal". Do you plan to implement some sort of Internationalization for text / buttons ?

**Comment by simplezhli** [comment]
>Do you plan to implement some sort of Internationalization for text / buttons ?

Maybe, but it ’s not the point.

**Comment by ghedwards** [comment]
Would you use https://pub.dev/packages/intl ?

**Comment by simplezhli** [comment]
Yes
